// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ravzvjtprjsuuoetplre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdnp2anRwcmpzdXVvZXRwbHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjU2ODEsImV4cCI6MjA1OTMwMTY4MX0.thfiRurv3cSZPnM-i2Z-d7gc_OzIuFHcnk-gTxCxHYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);